services:
  capture:
    image: ghcr.io/bluewave-labs/capture:latest
    container_name: capture
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    ports:
      - "59232:59232"
    environment:
      - API_SECRET=nilok3
      # - API_SECRET=${CAPTURE_API_SECRET}
      - GIN_MODE=release
    volumes:
      - /etc/os-release:/etc/os-release:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.docker.network=proxy"
    #   # Route for search domain
    #   - "traefik.http.routers.capture-searchdomain.entrypoints=websecure"
    #   - "traefik.http.routers.capture-searchdomain.rule=Host(`capture.${SEARCH_DOMAIN}`)"
    #   - "traefik.http.routers.capture-searchdomain.tls.certresolver=cloudflare"
    #   - "traefik.http.routers.capture-searchdomain.service=capture-service"
    #   # Service definition
    #   - "traefik.http.services.capture-service.loadbalancer.server.port=59232"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"